name: Build Test and Release Docker Image on Push

# https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    # Install all the dependencies
    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
        docker version

    # Build docker image
    - name: Build Docker Image
      run: |
        docker build -t adscert-image .

    # Run signer signatory
    - name: Run Signer Signatory Container
      run: |
        docker run -d -p 3000:3000 --name signer-container adscert-image ./adscert signatory --private_key "Ys83NKuuYxCVDUbmA671x3zAFsQ-EnNxmC2JLuBlGAU" --origin "adscerttestsigner.dev"

    # Run verifier signatory
    - name: Run Verifier Signatory Container
      run: |
        docker run -d -p 4000:4000 --name verifier-container adscert-image ./adscert signatory --server_port 4000 --metrics_port 4001 --private_key "6mkLbsTBKs0UwYLkBdw5ttJHzjpSZxof0A2rako-0qs" --origin "adscerttestverifier.dev"

    # # Run integration tests against docker container
    - name: Run Docker Integration Tests
      run: |
        cd cmd
        go test -v . -tags integration 
        
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Build and Release Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: adscert
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GITHUB_TOKEN }}

 