name: Build and Test Docker Image on Pull Request

# https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    # Install all the dependencies
    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
        docker version

    # Build docker image
    - name: Build Docker Image
      run: |
        docker build -t adscert-image .

    # Run signer signatory
    - name: Run Signer Signatory Container
      run: |
        docker run -d -p 3000:3000 --name signer-container adscert-image ./adscert signatory --server_port 3000 --metrics_port 3001 --private_key "Ys83NKuuYxCVDUbmA671x3zAFsQ-EnNxmC2JLuBlGAU" --origin "adscerttestsigner.dev"

    # Run verifier signatory
    - name: Run Verifier Signatory Container
      run: |
        docker run -d -p 4000:4000 --name verifier-container adscert-image ./adscert signatory --server_port 4000 --metrics_port 4001 --private_key "6mkLbsTBKs0UwYLkBdw5ttJHzjpSZxof0A2rako-0qs" --origin "adscerttestverifier.dev"

    # Run and test local receiver web server
    - name: Run Receiver Server
      run: |
        go run . testreceiver --server_port 5000 --verifier_address localhost:4000 &
        curl http://localhost:5000 -d "https://adscerttestverifier.dev" -H "X-Ads-Cert-Auth: from=adscerttestsigner.dev&from_key=LxqTmA&invoking=adscerttestverifier.dev&nonce=mBJo7EYj9XF9&status=1&timestamp=220810T142237&to=adscerttestverifier.dev&to_key=uNzTFA; sigb=ugN9tqMd6h0p&sigu=pxQd8BV20lHg"
        

    # # Run integration tests against docker container
    - name: Run Docker Integration Tests
      run: |
        cd cmd
        go test -v . -tags integration 
